#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  get-duckdb-version:
    name: Get DuckDB version
    runs-on: ubuntu-latest
    outputs:
      duckdb_version: ${{ steps.version.outputs.duckdb_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - id: version
        run: echo "duckdb_version=$(cat .github/duckdb-version)" >> $GITHUB_OUTPUT

  duckdb-next-build:
    name: Build extension binaries
    needs: get-duckdb-version
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: ${{ needs.get-duckdb-version.outputs.duckdb_version }}
      ci_tools_version: main
      extension_name: duckpgq

  code-quality-check:
    name: Code Quality Check
    needs: get-duckdb-version
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_code_quality.yml@main
    with:
      duckdb_version: ${{ needs.get-duckdb-version.outputs.duckdb_version }}
      ci_tools_version: main
      extension_name: duckpgq
      format_checks: 'format;tidy'
