name: Close Stale Issues

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight (UTC)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions."
          stale-pr-message: "This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions."
          days-before-stale: 90 # Number of days of inactivity before an issue or PR is marked stale
          days-before-close: 7 # Number of days after being marked stale before the issue or PR is closed
          stale-issue-label: "stale" # Label to apply to stale issues
          stale-pr-label: "stale" # Label to apply to stale pull requests
          exempt-issue-labels: "pinned, security, reproduced" # Issues with these labels will not be marked as stale
          exempt-pr-labels: "pinned, security" # PRs with these labels will not be marked as stale
          only-issue-labels: "" # Only issues with these labels will be checked (leave empty to check all issues)
          only-pr-labels: "" # Only PRs with these labels will be checked (leave empty to check all PRs)
          operations-per-run: 30 # Limit of actions to perform per run (avoid hitting rate limits)
